[package]
name = "rfnet"
version = "0.1.0"
authors = ["Val Vanderschaegen <valere.vanderschaegen@gmail.com>"]

[dependencies]
rfnet-core = { path = "rfnet-core" }
rfnet-web = { path = "rfnet-web" }
log = "0.4.1"
fern = "0.5.2"
clap = "2.29.2"
chrono = "0.4.0"

[workspace]