version: '3.2'
services:
  web:
    build: .
    volumes:
      - type: bind
        source: ./rfnet_hub
        target: /app
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres